#!/usr/bin/env bash
# Check if the correct number of arguments are passed
if [[ $# -ne 4 ]]; then
    echo "Usage: ${0#./} PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

FILE=$1
SERVER_IP=$2
USERNAME=$3
SSH_KEY=$4

scp -o StrictHostKeyChecking=no -i "$SSH_KEY" "$FILE" "$USERNAME"@"$SERVER_IP":~/