#!/usr/bin/env bash
# Bash script that displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi.
((i = 0))
while ((i < 10)); do
	echo "Best School"
	if ((i == 9)); then
		break
	fi
	if ((i == 8)); then
		echo "Hi"
	fi
	((i++))
done
