#!/usr/bin/env bash
# Make the container work with only nginx user in less than 7 lines
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
su -c "service nginx start" nginx
